'''
Created on Nov 3, 2012

@author: Majid Hameed
'''
def conjecture(n):
    '''
    
    Given any initial natural number, consider the sequence of numbers generated by repeatedly following the rule:

divide by two if the number is even or
multiply by 3 and add 1 if the number is odd.
The Collatz conjecture states that this sequence always terminates at 1. For example, the sequence generated by 23 is:

23, 70, 35, 106, 53, 160, 80, 40, 20, 10, 5, 16, 8, 4, 2, 1

Write a Python program that takes a global variable n and uses a timer callback to repeatedly apply the rule above to n. Use the code from the previous question as a template. I suggest that your code prints out the sequence of numbers generated by this rule. Run this program for n = 217. What is the largest number in the sequence generated by this starting value?

To test your code, starting at n = 23 generates a sequence with a maximum value of 160.
    '''
    list = [n]
    
    while n!=1:
        
        if n % 2 == 0:
            n = int(n/2)
        else:
            n = int(n*3) + 1    
        
        list.append(n)
    
    print (list)
    print ("max:" , max(list))
    
conjecture(217)
        